using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;

namespace Zipline2.BusinessLogic
{
    public class WcfServicesProxy
    {
        //The current Windows Phone app has a Service Reference folder with references
        //to the services.  When the services are added, the classes with references
        //are autogenerated. Then the phone app just has the following:

        //private PosServiceClient waiterClient;
        //private CheckHostClient checkClient;


        //See field DefaultBinding in Windows Phone App.
        //Don't seem to be using though....?
        //BasicHttpBinding bhttpb = new BasicHttpBinding();
        //{
        //    Security = new BasicHttpSecurity()
        //    {
        //        Mode = BasicHttpSecurityMode.None,
        //        Transport = new HttpTransportSecurity()
        //        {
        //            ProxyCredentialType = HttpProxyCredentialType.None,
        //            ClientCredentialType = HttpClientCredentialType.None
        //        }
        //    },
        //    BypassProxyOnLocal = true
        //};
        //whatever = new SomethingServiceClient(bhttpb, whoknows);

        //async void DoStuff()
        //{
        //    //dblResult = await Task.Run<double>(delegate { return whatever.Add(dblX, dblY); });
        //}


    }
}
