using System;
using System.Collections.Generic;
using System.Text;

namespace Zipline2.BusinessLogic.Enums
{
    public enum DrinkType
    {
        None,
        Water,
        LolaCola,
        StevieZ,
        LennieLemonLime,
        GinnieGingerAle,
        RubyRootBeer,
        AppleJuice,
        Lemonade,
        SweetTea,
        SweetArnoldPalmer,
        UnsweetArnoldPalmer,
        UnsweetTea,
        SodaWater,
        Milk,
        BottledCoke,
        HalfNHalfTea,
        DietCokeCan,
        SodaPitcher,
        Flight,
        SpecialSoda,
        Hefeweizen,
        FirstMagnitude72,
        EmployeeBeer,
        SwampHeadBigNoseIpa,
        PilsLagerOrBlondeAle,
        Beer12Oz,
        Guinness,
        OmissionPaleAle,
        Bud,
        BudLight,
        NaGenesee,
        JaiAlaiIpa,
        PinotGrigio,
        Chardonnay,
        WhiteZin,
        Rose,
        SauvBlanc,
        DouglasGreenSb,
        LeeseFitchCab,
        AlverdiSangiovese,
        Chianti,
        RedZinfandel,
        GreenTruckPetitiSyrah,
        ClayhouseRedBlend,
        YauquenMalbec,
        BodegasLaya,
        RegularCoffee,
        DecafCoffee,
        HotTea,
        HotCocoa,
        WineSpecial10,
        WineSpecial12,
        WineSpecial15,
        CorkageFee,
        WineSpecial14
    }
}
