//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DBTable", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class DBTable : object
    {
        
        private PosServiceReference.Guest_DB[] GuestsField;
        
        private decimal IDField;
        
        private bool IsClearField;
        
        private bool IsMainField;
        
        private bool IsSplitField;
        
        private bool IsSubField;
        
        private bool JoinedField;
        
        private int[] JoinedTableIDsField;
        
        private decimal MaxSizeField;
        
        private string NameField;
        
        private decimal[] SectionsField;
        
        private string ShapeField;
        
        private decimal[] SplitTableIDsField;
        
        private decimal StandardSizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PosServiceReference.Guest_DB[] Guests
        {
            get
            {
                return this.GuestsField;
            }
            set
            {
                this.GuestsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsClear
        {
            get
            {
                return this.IsClearField;
            }
            set
            {
                this.IsClearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMain
        {
            get
            {
                return this.IsMainField;
            }
            set
            {
                this.IsMainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSplit
        {
            get
            {
                return this.IsSplitField;
            }
            set
            {
                this.IsSplitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSub
        {
            get
            {
                return this.IsSubField;
            }
            set
            {
                this.IsSubField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Joined
        {
            get
            {
                return this.JoinedField;
            }
            set
            {
                this.JoinedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] JoinedTableIDs
        {
            get
            {
                return this.JoinedTableIDsField;
            }
            set
            {
                this.JoinedTableIDsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaxSize
        {
            get
            {
                return this.MaxSizeField;
            }
            set
            {
                this.MaxSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal[] Sections
        {
            get
            {
                return this.SectionsField;
            }
            set
            {
                this.SectionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shape
        {
            get
            {
                return this.ShapeField;
            }
            set
            {
                this.ShapeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal[] SplitTableIDs
        {
            get
            {
                return this.SplitTableIDsField;
            }
            set
            {
                this.SplitTableIDsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StandardSize
        {
            get
            {
                return this.StandardSizeField;
            }
            set
            {
                this.StandardSizeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Guest_DB", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PosServiceReference.TakeoutOrder))]
    public partial class Guest_DB : object
    {
        
        private bool CheckedOutField;
        
        private PosServiceReference.GuestComboItem[] ComboItemsField;
        
        private decimal IDField;
        
        private bool IsWholeField;
        
        private PosServiceReference.GuestItem[] ItemsField;
        
        private decimal TableIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CheckedOut
        {
            get
            {
                return this.CheckedOutField;
            }
            set
            {
                this.CheckedOutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PosServiceReference.GuestComboItem[] ComboItems
        {
            get
            {
                return this.ComboItemsField;
            }
            set
            {
                this.ComboItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWhole
        {
            get
            {
                return this.IsWholeField;
            }
            set
            {
                this.IsWholeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PosServiceReference.GuestItem[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TableID
        {
            get
            {
                return this.TableIDField;
            }
            set
            {
                this.TableIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TakeoutOrder", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class TakeoutOrder : PosServiceReference.Guest_DB
    {
        
        private string NameField;
        
        private string[] NotesField;
        
        private System.DateTime OrderPickupTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderPickupTime
        {
            get
            {
                return this.OrderPickupTimeField;
            }
            set
            {
                this.OrderPickupTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestComboItem", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class GuestComboItem : object
    {
        
        private decimal BasePriceField;
        
        private PosServiceReference.GuestItem[] ComboGuestItemsField;
        
        private decimal IDField;
        
        private string NameField;
        
        private decimal OrderComboIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BasePrice
        {
            get
            {
                return this.BasePriceField;
            }
            set
            {
                this.BasePriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PosServiceReference.GuestItem[] ComboGuestItems
        {
            get
            {
                return this.ComboGuestItemsField;
            }
            set
            {
                this.ComboGuestItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderComboID
        {
            get
            {
                return this.OrderComboIDField;
            }
            set
            {
                this.OrderComboIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestItem", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class GuestItem : PosServiceReference.DBItem
    {
        
        private decimal BasePriceField;
        
        private PosServiceReference.GuestModifier[] DefaultModifiersField;
        
        private PosServiceReference.GuestModifier[] ModsField;
        
        private string[] NoteField;
        
        private decimal OrderIDField;
        
        private bool OrderSentField;
        
        private decimal PlateIDField;
        
        private decimal SelectSizeIDField;
        
        private PosServiceReference.GuestModifier[] SidesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BasePrice
        {
            get
            {
                return this.BasePriceField;
            }
            set
            {
                this.BasePriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PosServiceReference.GuestModifier[] DefaultModifiers
        {
            get
            {
                return this.DefaultModifiersField;
            }
            set
            {
                this.DefaultModifiersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PosServiceReference.GuestModifier[] Mods
        {
            get
            {
                return this.ModsField;
            }
            set
            {
                this.ModsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OrderSent
        {
            get
            {
                return this.OrderSentField;
            }
            set
            {
                this.OrderSentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PlateID
        {
            get
            {
                return this.PlateIDField;
            }
            set
            {
                this.PlateIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SelectSizeID
        {
            get
            {
                return this.SelectSizeIDField;
            }
            set
            {
                this.SelectSizeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PosServiceReference.GuestModifier[] Sides
        {
            get
            {
                return this.SidesField;
            }
            set
            {
                this.SidesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DBItem", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PosServiceReference.ComboDBItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PosServiceReference.GuestItem))]
    public partial class DBItem : object
    {
        
        private bool AvailabilityField;
        
        private bool CanBeHalfField;
        
        private string DescriptionField;
        
        private bool HasAllModsField;
        
        private bool HasRequiredModsField;
        
        private decimal IDField;
        
        private string LongNameField;
        
        private bool NonTaxableField;
        
        private string SelectCommandField;
        
        private string ShortNameField;
        
        private System.Collections.Generic.Dictionary<decimal, PosServiceReference.SizeData> SizeTableField;
        
        private bool StackableField;
        
        private decimal SubCategoryIDField;
        
        private string SubCategoryNameField;
        
        private string SuperCategoryField;
        
        private decimal SuperCategoryIDField;
        
        private PosServiceReference.Tiered[] TieredPricingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Availability
        {
            get
            {
                return this.AvailabilityField;
            }
            set
            {
                this.AvailabilityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanBeHalf
        {
            get
            {
                return this.CanBeHalfField;
            }
            set
            {
                this.CanBeHalfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasAllMods
        {
            get
            {
                return this.HasAllModsField;
            }
            set
            {
                this.HasAllModsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasRequiredMods
        {
            get
            {
                return this.HasRequiredModsField;
            }
            set
            {
                this.HasRequiredModsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LongName
        {
            get
            {
                return this.LongNameField;
            }
            set
            {
                this.LongNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NonTaxable
        {
            get
            {
                return this.NonTaxableField;
            }
            set
            {
                this.NonTaxableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectCommand
        {
            get
            {
                return this.SelectCommandField;
            }
            set
            {
                this.SelectCommandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName
        {
            get
            {
                return this.ShortNameField;
            }
            set
            {
                this.ShortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<decimal, PosServiceReference.SizeData> SizeTable
        {
            get
            {
                return this.SizeTableField;
            }
            set
            {
                this.SizeTableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Stackable
        {
            get
            {
                return this.StackableField;
            }
            set
            {
                this.StackableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SubCategoryID
        {
            get
            {
                return this.SubCategoryIDField;
            }
            set
            {
                this.SubCategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategoryName
        {
            get
            {
                return this.SubCategoryNameField;
            }
            set
            {
                this.SubCategoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuperCategory
        {
            get
            {
                return this.SuperCategoryField;
            }
            set
            {
                this.SuperCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SuperCategoryID
        {
            get
            {
                return this.SuperCategoryIDField;
            }
            set
            {
                this.SuperCategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PosServiceReference.Tiered[] TieredPricing
        {
            get
            {
                return this.TieredPricingField;
            }
            set
            {
                this.TieredPricingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComboDBItem", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class ComboDBItem : PosServiceReference.DBItem
    {
        
        private PosServiceReference.SizeData[] AvailableSizesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PosServiceReference.SizeData[] AvailableSizes
        {
            get
            {
                return this.AvailableSizesField;
            }
            set
            {
                this.AvailableSizesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SizeData", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class SizeData : object
    {
        
        private decimal IDField;
        
        private string NameField;
        
        private decimal PriceField;
        
        private string ReceiptNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptName
        {
            get
            {
                return this.ReceiptNameField;
            }
            set
            {
                this.ReceiptNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tiered", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class Tiered : object
    {
        
        private decimal ModifierCountField;
        
        private decimal ModifierTierIDField;
        
        private decimal PriceAdjustmentField;
        
        private decimal SizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ModifierCount
        {
            get
            {
                return this.ModifierCountField;
            }
            set
            {
                this.ModifierCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ModifierTierID
        {
            get
            {
                return this.ModifierTierIDField;
            }
            set
            {
                this.ModifierTierIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceAdjustment
        {
            get
            {
                return this.PriceAdjustmentField;
            }
            set
            {
                this.PriceAdjustmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Size
        {
            get
            {
                return this.SizeField;
            }
            set
            {
                this.SizeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestModifier", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class GuestModifier : PosServiceReference.DBModifier
    {
        
        private string HalfField;
        
        private decimal MultiplierField;
        
        private bool SpecialCountField;
        
        private string StateField;
        
        private bool isDefaultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Half
        {
            get
            {
                return this.HalfField;
            }
            set
            {
                this.HalfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Multiplier
        {
            get
            {
                return this.MultiplierField;
            }
            set
            {
                this.MultiplierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SpecialCount
        {
            get
            {
                return this.SpecialCountField;
            }
            set
            {
                this.SpecialCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isDefault
        {
            get
            {
                return this.isDefaultField;
            }
            set
            {
                this.isDefaultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DBModifier", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PosServiceReference.GuestModifier))]
    public partial class DBModifier : object
    {
        
        private int BaseCountField;
        
        private decimal BasePriceField;
        
        private decimal IDField;
        
        private string NameField;
        
        private decimal PriorityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BaseCount
        {
            get
            {
                return this.BaseCountField;
            }
            set
            {
                this.BaseCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BasePrice
        {
            get
            {
                return this.BasePriceField;
            }
            set
            {
                this.BasePriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DBUser", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class DBUser : object
    {
        
        private string DescriptionField;
        
        private decimal IDField;
        
        private string NameField;
        
        private string PinField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin
        {
            get
            {
                return this.PinField;
            }
            set
            {
                this.PinField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DBModGroup", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class DBModGroup : object
    {
        
        private decimal IDField;
        
        private int MinSelectionsField;
        
        private string NameField;
        
        private PosServiceReference.DBModifier[] SelectionListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinSelections
        {
            get
            {
                return this.MinSelectionsField;
            }
            set
            {
                this.MinSelectionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PosServiceReference.DBModifier[] SelectionList
        {
            get
            {
                return this.SelectionListField;
            }
            set
            {
                this.SelectionListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemInfo", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class ItemInfo : object
    {
        
        private string DescriptionField;
        
        private PosServiceReference.PictureFile PictureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PosServiceReference.PictureFile Picture
        {
            get
            {
                return this.PictureField;
            }
            set
            {
                this.PictureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PictureFile", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class PictureFile : object
    {
        
        private string PictureNameField;
        
        private byte[] PictureStreamField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PictureName
        {
            get
            {
                return this.PictureNameField;
            }
            set
            {
                this.PictureNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] PictureStream
        {
            get
            {
                return this.PictureStreamField;
            }
            set
            {
                this.PictureStreamField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManagerSettings", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class ManagerSettings : object
    {
        
        private bool AutoSendOrdersField;
        
        private string[] CategoryOrderField;
        
        private string ComboNameField;
        
        private int DefaultSeatField;
        
        private string GuestFontSizeField;
        
        private decimal MenuVersionField;
        
        private string SeatFontSizeField;
        
        private bool ShowGuestNumField;
        
        private bool ShowSeatNumField;
        
        private bool ShowTableNumField;
        
        private int SliderIncreamentsField;
        
        private int SliderMaxField;
        
        private int SliderMinField;
        
        private string TableFontSizeField;
        
        private System.Collections.Generic.Dictionary<System.TimeSpan, string> TakeoutEscalationField;
        
        private decimal TaxRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AutoSendOrders
        {
            get
            {
                return this.AutoSendOrdersField;
            }
            set
            {
                this.AutoSendOrdersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CategoryOrder
        {
            get
            {
                return this.CategoryOrderField;
            }
            set
            {
                this.CategoryOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComboName
        {
            get
            {
                return this.ComboNameField;
            }
            set
            {
                this.ComboNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DefaultSeat
        {
            get
            {
                return this.DefaultSeatField;
            }
            set
            {
                this.DefaultSeatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuestFontSize
        {
            get
            {
                return this.GuestFontSizeField;
            }
            set
            {
                this.GuestFontSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MenuVersion
        {
            get
            {
                return this.MenuVersionField;
            }
            set
            {
                this.MenuVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeatFontSize
        {
            get
            {
                return this.SeatFontSizeField;
            }
            set
            {
                this.SeatFontSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowGuestNum
        {
            get
            {
                return this.ShowGuestNumField;
            }
            set
            {
                this.ShowGuestNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowSeatNum
        {
            get
            {
                return this.ShowSeatNumField;
            }
            set
            {
                this.ShowSeatNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowTableNum
        {
            get
            {
                return this.ShowTableNumField;
            }
            set
            {
                this.ShowTableNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SliderIncreaments
        {
            get
            {
                return this.SliderIncreamentsField;
            }
            set
            {
                this.SliderIncreamentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SliderMax
        {
            get
            {
                return this.SliderMaxField;
            }
            set
            {
                this.SliderMaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SliderMin
        {
            get
            {
                return this.SliderMinField;
            }
            set
            {
                this.SliderMinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableFontSize
        {
            get
            {
                return this.TableFontSizeField;
            }
            set
            {
                this.TableFontSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<System.TimeSpan, string> TakeoutEscalation
        {
            get
            {
                return this.TakeoutEscalationField;
            }
            set
            {
                this.TakeoutEscalationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxRate
        {
            get
            {
                return this.TaxRateField;
            }
            set
            {
                this.TaxRateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComboItem", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class ComboItem : object
    {
        
        private decimal BasePriceField;
        
        private PosServiceReference.ComboDBItem[] ComboItemsField;
        
        private decimal IDField;
        
        private string NameField;
        
        private decimal SubCategoryIDField;
        
        private string SubCategoryNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BasePrice
        {
            get
            {
                return this.BasePriceField;
            }
            set
            {
                this.BasePriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PosServiceReference.ComboDBItem[] ComboItems
        {
            get
            {
                return this.ComboItemsField;
            }
            set
            {
                this.ComboItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SubCategoryID
        {
            get
            {
                return this.SubCategoryIDField;
            }
            set
            {
                this.SubCategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategoryName
        {
            get
            {
                return this.SubCategoryNameField;
            }
            set
            {
                this.SubCategoryNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CateringOrder", Namespace="http://schemas.datacontract.org/2004/07/Staunch.POS.Classes")]
    public partial class CateringOrder : object
    {
        
        private decimal BasePriceField;
        
        private int CateringIDField;
        
        private bool CheckedOutField;
        
        private string CompanyNameField;
        
        private System.DateTime DateOrderedField;
        
        private decimal DeliveryFeeField;
        
        private bool DessertsField;
        
        private string DriverNameField;
        
        private string EmailField;
        
        private string ManagerNotesField;
        
        private string NotesField;
        
        private int NumDessertPeopleField;
        
        private int NumPizzaPeopleField;
        
        private int NumSaladPeopleField;
        
        private string PhoneField;
        
        private System.DateTime PickupDateField;
        
        private decimal PriceAdjustField;
        
        private decimal PricePerDessertPersonField;
        
        private decimal PricePerPizzaPersonField;
        
        private decimal PricePerSaladPersonField;
        
        private bool SaladsField;
        
        private decimal ServiceFeeField;
        
        private decimal ServiceFeePercentField;
        
        private decimal SubTotalField;
        
        private PosServiceReference.TakeoutOrder TakeoutGuestField;
        
        private decimal TakeoutGuestIDField;
        
        private bool TaxField;
        
        private decimal TaxAmountField;
        
        private bool TaxPriceAdjustField;
        
        private decimal TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BasePrice
        {
            get
            {
                return this.BasePriceField;
            }
            set
            {
                this.BasePriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CateringID
        {
            get
            {
                return this.CateringIDField;
            }
            set
            {
                this.CateringIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CheckedOut
        {
            get
            {
                return this.CheckedOutField;
            }
            set
            {
                this.CheckedOutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOrdered
        {
            get
            {
                return this.DateOrderedField;
            }
            set
            {
                this.DateOrderedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DeliveryFee
        {
            get
            {
                return this.DeliveryFeeField;
            }
            set
            {
                this.DeliveryFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Desserts
        {
            get
            {
                return this.DessertsField;
            }
            set
            {
                this.DessertsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverName
        {
            get
            {
                return this.DriverNameField;
            }
            set
            {
                this.DriverNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerNotes
        {
            get
            {
                return this.ManagerNotesField;
            }
            set
            {
                this.ManagerNotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumDessertPeople
        {
            get
            {
                return this.NumDessertPeopleField;
            }
            set
            {
                this.NumDessertPeopleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumPizzaPeople
        {
            get
            {
                return this.NumPizzaPeopleField;
            }
            set
            {
                this.NumPizzaPeopleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumSaladPeople
        {
            get
            {
                return this.NumSaladPeopleField;
            }
            set
            {
                this.NumSaladPeopleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PickupDate
        {
            get
            {
                return this.PickupDateField;
            }
            set
            {
                this.PickupDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceAdjust
        {
            get
            {
                return this.PriceAdjustField;
            }
            set
            {
                this.PriceAdjustField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PricePerDessertPerson
        {
            get
            {
                return this.PricePerDessertPersonField;
            }
            set
            {
                this.PricePerDessertPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PricePerPizzaPerson
        {
            get
            {
                return this.PricePerPizzaPersonField;
            }
            set
            {
                this.PricePerPizzaPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PricePerSaladPerson
        {
            get
            {
                return this.PricePerSaladPersonField;
            }
            set
            {
                this.PricePerSaladPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Salads
        {
            get
            {
                return this.SaladsField;
            }
            set
            {
                this.SaladsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ServiceFee
        {
            get
            {
                return this.ServiceFeeField;
            }
            set
            {
                this.ServiceFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ServiceFeePercent
        {
            get
            {
                return this.ServiceFeePercentField;
            }
            set
            {
                this.ServiceFeePercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SubTotal
        {
            get
            {
                return this.SubTotalField;
            }
            set
            {
                this.SubTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PosServiceReference.TakeoutOrder TakeoutGuest
        {
            get
            {
                return this.TakeoutGuestField;
            }
            set
            {
                this.TakeoutGuestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TakeoutGuestID
        {
            get
            {
                return this.TakeoutGuestIDField;
            }
            set
            {
                this.TakeoutGuestIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Tax
        {
            get
            {
                return this.TaxField;
            }
            set
            {
                this.TaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxAmount
        {
            get
            {
                return this.TaxAmountField;
            }
            set
            {
                this.TaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TaxPriceAdjust
        {
            get
            {
                return this.TaxPriceAdjustField;
            }
            set
            {
                this.TaxPriceAdjustField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PosServiceReference.IPosService")]
    public interface IPosService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetTable", ReplyAction="http://tempuri.org/IPosService/GetTableResponse")]
        System.Threading.Tasks.Task<PosServiceReference.DBTable> GetTableAsync(int tableNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/ValidateUser", ReplyAction="http://tempuri.org/IPosService/ValidateUserResponse")]
        System.Threading.Tasks.Task<PosServiceReference.DBUser> ValidateUserAsync(decimal AuthenticationID, string UserName, string Pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetTableInfo", ReplyAction="http://tempuri.org/IPosService/GetTableInfoResponse")]
        System.Threading.Tasks.Task<PosServiceReference.DBTable[]> GetTableInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/FillTables", ReplyAction="http://tempuri.org/IPosService/FillTablesResponse")]
        System.Threading.Tasks.Task<PosServiceReference.DBTable[]> FillTablesAsync(decimal userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetMenu", ReplyAction="http://tempuri.org/IPosService/GetMenuResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, PosServiceReference.DBItem[]>> GetMenuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetModifiers", ReplyAction="http://tempuri.org/IPosService/GetModifiersResponse")]
        System.Threading.Tasks.Task<PosServiceReference.DBModGroup[]> GetModifiersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetAvailablePaymentOptions", ReplyAction="http://tempuri.org/IPosService/GetAvailablePaymentOptionsResponse")]
        System.Threading.Tasks.Task<string[]> GetAvailablePaymentOptionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/UpdateTables", ReplyAction="http://tempuri.org/IPosService/UpdateTablesResponse")]
        System.Threading.Tasks.Task UpdateTablesAsync(PosServiceReference.DBTable[] updatedTables, decimal userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetGratuityLimit", ReplyAction="http://tempuri.org/IPosService/GetGratuityLimitResponse")]
        System.Threading.Tasks.Task<int> GetGratuityLimitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetTaxRate", ReplyAction="http://tempuri.org/IPosService/GetTaxRateResponse")]
        System.Threading.Tasks.Task<decimal> GetTaxRateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetGratuityRate", ReplyAction="http://tempuri.org/IPosService/GetGratuityRateResponse")]
        System.Threading.Tasks.Task<decimal> GetGratuityRateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/DoAutoGratuity", ReplyAction="http://tempuri.org/IPosService/DoAutoGratuityResponse")]
        System.Threading.Tasks.Task<bool> DoAutoGratuityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetCategoryNames", ReplyAction="http://tempuri.org/IPosService/GetCategoryNamesResponse")]
        System.Threading.Tasks.Task<string[]> GetCategoryNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetNextGuestIDs", ReplyAction="http://tempuri.org/IPosService/GetNextGuestIDsResponse")]
        System.Threading.Tasks.Task<decimal[]> GetNextGuestIDsAsync(int num, decimal userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/RemoveGuest", ReplyAction="http://tempuri.org/IPosService/RemoveGuestResponse")]
        System.Threading.Tasks.Task<bool> RemoveGuestAsync(decimal GuestID, bool RemoveOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/RemoveItem", ReplyAction="http://tempuri.org/IPosService/RemoveItemResponse")]
        System.Threading.Tasks.Task<bool> RemoveItemAsync(decimal GuestID, decimal OrderID, decimal UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetItemInfo", ReplyAction="http://tempuri.org/IPosService/GetItemInfoResponse")]
        System.Threading.Tasks.Task<PosServiceReference.ItemInfo> GetItemInfoAsync(decimal ItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetThumbnails", ReplyAction="http://tempuri.org/IPosService/GetThumbnailsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<decimal, PosServiceReference.PictureFile>> GetThumbnailsAsync(decimal[] ItemIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetOrders", ReplyAction="http://tempuri.org/IPosService/GetOrdersResponse")]
        System.Threading.Tasks.Task<PosServiceReference.GuestItem[]> GetOrdersAsync(decimal TableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/SendOrders", ReplyAction="http://tempuri.org/IPosService/SendOrdersResponse")]
        System.Threading.Tasks.Task SendOrdersAsync(decimal[] OrderIDs, decimal UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/RemoveSentOrder", ReplyAction="http://tempuri.org/IPosService/RemoveSentOrderResponse")]
        System.Threading.Tasks.Task RemoveSentOrderAsync(decimal[] OrderIDs, decimal UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/SaveUserSettings", ReplyAction="http://tempuri.org/IPosService/SaveUserSettingsResponse")]
        System.Threading.Tasks.Task<bool> SaveUserSettingsAsync(PosServiceReference.DBUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/MoveGuests", ReplyAction="http://tempuri.org/IPosService/MoveGuestsResponse")]
        System.Threading.Tasks.Task<bool> MoveGuestsAsync(decimal[] GuestIDs, decimal NewTableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/SplitTable", ReplyAction="http://tempuri.org/IPosService/SplitTableResponse")]
        System.Threading.Tasks.Task<bool> SplitTableAsync(decimal TableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/HasUnsentOrders", ReplyAction="http://tempuri.org/IPosService/HasUnsentOrdersResponse")]
        System.Threading.Tasks.Task<bool> HasUnsentOrdersAsync(decimal TableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetManagerSettings", ReplyAction="http://tempuri.org/IPosService/GetManagerSettingsResponse")]
        System.Threading.Tasks.Task<PosServiceReference.ManagerSettings> GetManagerSettingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/Logout", ReplyAction="http://tempuri.org/IPosService/LogoutResponse")]
        System.Threading.Tasks.Task<bool> LogoutAsync(decimal UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/Ping", ReplyAction="http://tempuri.org/IPosService/PingResponse")]
        System.Threading.Tasks.Task<int> PingAsync(int Delay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetRequiredMods", ReplyAction="http://tempuri.org/IPosService/GetRequiredModsResponse")]
        System.Threading.Tasks.Task<PosServiceReference.DBModGroup[]> GetRequiredModsAsync(decimal ItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetAllMods", ReplyAction="http://tempuri.org/IPosService/GetAllModsResponse")]
        System.Threading.Tasks.Task<PosServiceReference.DBModGroup[]> GetAllModsAsync(decimal ItemID, decimal SizeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetComboMenu", ReplyAction="http://tempuri.org/IPosService/GetComboMenuResponse")]
        System.Threading.Tasks.Task<PosServiceReference.ComboItem[]> GetComboMenuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/RemoveGuestCombo", ReplyAction="http://tempuri.org/IPosService/RemoveGuestComboResponse")]
        System.Threading.Tasks.Task<bool> RemoveGuestComboAsync(decimal GuestID, decimal OrderComboID, decimal UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/CombineOrders", ReplyAction="http://tempuri.org/IPosService/CombineOrdersResponse")]
        System.Threading.Tasks.Task<bool> CombineOrdersAsync(decimal DestinationGuestID, decimal[] GuestsToMoveIDs, bool RemoveAfterCombine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/ClearTable", ReplyAction="http://tempuri.org/IPosService/ClearTableResponse")]
        System.Threading.Tasks.Task<bool> ClearTableAsync(decimal TableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/SubmitTakeout", ReplyAction="http://tempuri.org/IPosService/SubmitTakeoutResponse")]
        System.Threading.Tasks.Task<PosServiceReference.TakeoutOrder> SubmitTakeoutAsync(PosServiceReference.TakeoutOrder TakeoutGuest, decimal UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetTakeoutOrders", ReplyAction="http://tempuri.org/IPosService/GetTakeoutOrdersResponse")]
        System.Threading.Tasks.Task<PosServiceReference.TakeoutOrder[]> GetTakeoutOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetTakeoutOrder", ReplyAction="http://tempuri.org/IPosService/GetTakeoutOrderResponse")]
        System.Threading.Tasks.Task<PosServiceReference.TakeoutOrder> GetTakeoutOrderAsync(decimal GuestID, decimal CheckID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/SendTakeout", ReplyAction="http://tempuri.org/IPosService/SendTakeoutResponse")]
        System.Threading.Tasks.Task SendTakeoutAsync(PosServiceReference.TakeoutOrder TakeoutGuest, decimal UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/ClearTakeoutOrder", ReplyAction="http://tempuri.org/IPosService/ClearTakeoutOrderResponse")]
        System.Threading.Tasks.Task<bool> ClearTakeoutOrderAsync(decimal TakeoutID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/ListUnsentOrders", ReplyAction="http://tempuri.org/IPosService/ListUnsentOrdersResponse")]
        System.Threading.Tasks.Task<decimal[]> ListUnsentOrdersAsync(decimal[] TableIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/PrintMoveNotice", ReplyAction="http://tempuri.org/IPosService/PrintMoveNoticeResponse")]
        System.Threading.Tasks.Task<bool> PrintMoveNoticeAsync(decimal[] orderIDs, decimal fromTableID, decimal toTableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetModsForAllItems", ReplyAction="http://tempuri.org/IPosService/GetModsForAllItemsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<decimal, System.Collections.Generic.Dictionary<decimal, PosServiceReference.DBModGroup[]>>> GetModsForAllItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetSpecialItems", ReplyAction="http://tempuri.org/IPosService/GetSpecialItemsResponse")]
        System.Threading.Tasks.Task<PosServiceReference.DBItem[]> GetSpecialItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetTablesForSection", ReplyAction="http://tempuri.org/IPosService/GetTablesForSectionResponse")]
        System.Threading.Tasks.Task<PosServiceReference.DBTable[]> GetTablesForSectionAsync(decimal sectionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/ChangeItemSize", ReplyAction="http://tempuri.org/IPosService/ChangeItemSizeResponse")]
        System.Threading.Tasks.Task<bool> ChangeItemSizeAsync(decimal orderID, decimal newSizeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetUser", ReplyAction="http://tempuri.org/IPosService/GetUserResponse")]
        System.Threading.Tasks.Task<PosServiceReference.DBUser> GetUserAsync(string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/CancelTakeout", ReplyAction="http://tempuri.org/IPosService/CancelTakeoutResponse")]
        System.Threading.Tasks.Task<bool> CancelTakeoutAsync(decimal TakeoutGuestID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetLSEOrders", ReplyAction="http://tempuri.org/IPosService/GetLSEOrdersResponse")]
        System.Threading.Tasks.Task<PosServiceReference.TakeoutOrder[]> GetLSEOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/SubmitLSETakeout", ReplyAction="http://tempuri.org/IPosService/SubmitLSETakeoutResponse")]
        System.Threading.Tasks.Task<PosServiceReference.TakeoutOrder> SubmitLSETakeoutAsync(PosServiceReference.TakeoutOrder TakeoutGuest, decimal UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/PriceOrder", ReplyAction="http://tempuri.org/IPosService/PriceOrderResponse")]
        System.Threading.Tasks.Task<PosServiceReference.Guest_DB> PriceOrderAsync(PosServiceReference.Guest_DB guest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/PrintKitchenNote", ReplyAction="http://tempuri.org/IPosService/PrintKitchenNoteResponse")]
        System.Threading.Tasks.Task PrintKitchenNoteAsync(string note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/RemoveOrderFromPlate", ReplyAction="http://tempuri.org/IPosService/RemoveOrderFromPlateResponse")]
        System.Threading.Tasks.Task<bool> RemoveOrderFromPlateAsync(decimal OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/AddOrderToPlate", ReplyAction="http://tempuri.org/IPosService/AddOrderToPlateResponse")]
        System.Threading.Tasks.Task<bool> AddOrderToPlateAsync(decimal OrderID, decimal PlateID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/AddOrdersToPlate", ReplyAction="http://tempuri.org/IPosService/AddOrdersToPlateResponse")]
        System.Threading.Tasks.Task<bool> AddOrdersToPlateAsync(decimal[] orderIds, decimal plateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/RemoveMultipleFromPlate", ReplyAction="http://tempuri.org/IPosService/RemoveMultipleFromPlateResponse")]
        System.Threading.Tasks.Task<bool> RemoveMultipleFromPlateAsync(decimal[] orderIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/SubmitCatering", ReplyAction="http://tempuri.org/IPosService/SubmitCateringResponse")]
        System.Threading.Tasks.Task<PosServiceReference.CateringOrder> SubmitCateringAsync(PosServiceReference.CateringOrder catering, decimal UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetCateringTakeouts", ReplyAction="http://tempuri.org/IPosService/GetCateringTakeoutsResponse")]
        System.Threading.Tasks.Task<PosServiceReference.TakeoutOrder[]> GetCateringTakeoutsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetCateringOrder", ReplyAction="http://tempuri.org/IPosService/GetCateringOrderResponse")]
        System.Threading.Tasks.Task<PosServiceReference.CateringOrder> GetCateringOrderAsync(decimal TakeoutID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetAllCateringOrdersInfo", ReplyAction="http://tempuri.org/IPosService/GetAllCateringOrdersInfoResponse")]
        System.Threading.Tasks.Task<PosServiceReference.CateringOrder[]> GetAllCateringOrdersInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/SendCateringTakeout", ReplyAction="http://tempuri.org/IPosService/SendCateringTakeoutResponse")]
        System.Threading.Tasks.Task SendCateringTakeoutAsync(PosServiceReference.TakeoutOrder TakeoutGuest, decimal UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/GetTableSummary", ReplyAction="http://tempuri.org/IPosService/GetTableSummaryResponse")]
        System.Threading.Tasks.Task<PosServiceReference.DBTable[]> GetTableSummaryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPosService/PrintCateringOrder", ReplyAction="http://tempuri.org/IPosService/PrintCateringOrderResponse")]
        System.Threading.Tasks.Task PrintCateringOrderAsync(PosServiceReference.CateringOrder catering, decimal UserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IPosServiceChannel : PosServiceReference.IPosService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class PosServiceClient : System.ServiceModel.ClientBase<PosServiceReference.IPosService>, PosServiceReference.IPosService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PosServiceClient() : 
                base(PosServiceClient.GetDefaultBinding(), PosServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPosService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PosServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PosServiceClient.GetBindingForEndpoint(endpointConfiguration), PosServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PosServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PosServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PosServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PosServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.DBTable> GetTableAsync(int tableNum)
        {
            return base.Channel.GetTableAsync(tableNum);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.DBUser> ValidateUserAsync(decimal AuthenticationID, string UserName, string Pin)
        {
            return base.Channel.ValidateUserAsync(AuthenticationID, UserName, Pin);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.DBTable[]> GetTableInfoAsync()
        {
            return base.Channel.GetTableInfoAsync();
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.DBTable[]> FillTablesAsync(decimal userID)
        {
            return base.Channel.FillTablesAsync(userID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, PosServiceReference.DBItem[]>> GetMenuAsync()
        {
            return base.Channel.GetMenuAsync();
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.DBModGroup[]> GetModifiersAsync()
        {
            return base.Channel.GetModifiersAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAvailablePaymentOptionsAsync()
        {
            return base.Channel.GetAvailablePaymentOptionsAsync();
        }
        
        public System.Threading.Tasks.Task UpdateTablesAsync(PosServiceReference.DBTable[] updatedTables, decimal userID)
        {
            return base.Channel.UpdateTablesAsync(updatedTables, userID);
        }
        
        public System.Threading.Tasks.Task<int> GetGratuityLimitAsync()
        {
            return base.Channel.GetGratuityLimitAsync();
        }
        
        public System.Threading.Tasks.Task<decimal> GetTaxRateAsync()
        {
            return base.Channel.GetTaxRateAsync();
        }
        
        public System.Threading.Tasks.Task<decimal> GetGratuityRateAsync()
        {
            return base.Channel.GetGratuityRateAsync();
        }
        
        public System.Threading.Tasks.Task<bool> DoAutoGratuityAsync()
        {
            return base.Channel.DoAutoGratuityAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCategoryNamesAsync()
        {
            return base.Channel.GetCategoryNamesAsync();
        }
        
        public System.Threading.Tasks.Task<decimal[]> GetNextGuestIDsAsync(int num, decimal userID)
        {
            return base.Channel.GetNextGuestIDsAsync(num, userID);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveGuestAsync(decimal GuestID, bool RemoveOrder)
        {
            return base.Channel.RemoveGuestAsync(GuestID, RemoveOrder);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveItemAsync(decimal GuestID, decimal OrderID, decimal UserID)
        {
            return base.Channel.RemoveItemAsync(GuestID, OrderID, UserID);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.ItemInfo> GetItemInfoAsync(decimal ItemID)
        {
            return base.Channel.GetItemInfoAsync(ItemID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<decimal, PosServiceReference.PictureFile>> GetThumbnailsAsync(decimal[] ItemIDs)
        {
            return base.Channel.GetThumbnailsAsync(ItemIDs);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.GuestItem[]> GetOrdersAsync(decimal TableID)
        {
            return base.Channel.GetOrdersAsync(TableID);
        }
        
        public System.Threading.Tasks.Task SendOrdersAsync(decimal[] OrderIDs, decimal UserID)
        {
            return base.Channel.SendOrdersAsync(OrderIDs, UserID);
        }
        
        public System.Threading.Tasks.Task RemoveSentOrderAsync(decimal[] OrderIDs, decimal UserID)
        {
            return base.Channel.RemoveSentOrderAsync(OrderIDs, UserID);
        }
        
        public System.Threading.Tasks.Task<bool> SaveUserSettingsAsync(PosServiceReference.DBUser user)
        {
            return base.Channel.SaveUserSettingsAsync(user);
        }
        
        public System.Threading.Tasks.Task<bool> MoveGuestsAsync(decimal[] GuestIDs, decimal NewTableID)
        {
            return base.Channel.MoveGuestsAsync(GuestIDs, NewTableID);
        }
        
        public System.Threading.Tasks.Task<bool> SplitTableAsync(decimal TableID)
        {
            return base.Channel.SplitTableAsync(TableID);
        }
        
        public System.Threading.Tasks.Task<bool> HasUnsentOrdersAsync(decimal TableID)
        {
            return base.Channel.HasUnsentOrdersAsync(TableID);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.ManagerSettings> GetManagerSettingsAsync()
        {
            return base.Channel.GetManagerSettingsAsync();
        }
        
        public System.Threading.Tasks.Task<bool> LogoutAsync(decimal UserID)
        {
            return base.Channel.LogoutAsync(UserID);
        }
        
        public System.Threading.Tasks.Task<int> PingAsync(int Delay)
        {
            return base.Channel.PingAsync(Delay);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.DBModGroup[]> GetRequiredModsAsync(decimal ItemID)
        {
            return base.Channel.GetRequiredModsAsync(ItemID);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.DBModGroup[]> GetAllModsAsync(decimal ItemID, decimal SizeID)
        {
            return base.Channel.GetAllModsAsync(ItemID, SizeID);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.ComboItem[]> GetComboMenuAsync()
        {
            return base.Channel.GetComboMenuAsync();
        }
        
        public System.Threading.Tasks.Task<bool> RemoveGuestComboAsync(decimal GuestID, decimal OrderComboID, decimal UserID)
        {
            return base.Channel.RemoveGuestComboAsync(GuestID, OrderComboID, UserID);
        }
        
        public System.Threading.Tasks.Task<bool> CombineOrdersAsync(decimal DestinationGuestID, decimal[] GuestsToMoveIDs, bool RemoveAfterCombine)
        {
            return base.Channel.CombineOrdersAsync(DestinationGuestID, GuestsToMoveIDs, RemoveAfterCombine);
        }
        
        public System.Threading.Tasks.Task<bool> ClearTableAsync(decimal TableID)
        {
            return base.Channel.ClearTableAsync(TableID);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.TakeoutOrder> SubmitTakeoutAsync(PosServiceReference.TakeoutOrder TakeoutGuest, decimal UserID)
        {
            return base.Channel.SubmitTakeoutAsync(TakeoutGuest, UserID);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.TakeoutOrder[]> GetTakeoutOrdersAsync()
        {
            return base.Channel.GetTakeoutOrdersAsync();
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.TakeoutOrder> GetTakeoutOrderAsync(decimal GuestID, decimal CheckID)
        {
            return base.Channel.GetTakeoutOrderAsync(GuestID, CheckID);
        }
        
        public System.Threading.Tasks.Task SendTakeoutAsync(PosServiceReference.TakeoutOrder TakeoutGuest, decimal UserID)
        {
            return base.Channel.SendTakeoutAsync(TakeoutGuest, UserID);
        }
        
        public System.Threading.Tasks.Task<bool> ClearTakeoutOrderAsync(decimal TakeoutID)
        {
            return base.Channel.ClearTakeoutOrderAsync(TakeoutID);
        }
        
        public System.Threading.Tasks.Task<decimal[]> ListUnsentOrdersAsync(decimal[] TableIDList)
        {
            return base.Channel.ListUnsentOrdersAsync(TableIDList);
        }
        
        public System.Threading.Tasks.Task<bool> PrintMoveNoticeAsync(decimal[] orderIDs, decimal fromTableID, decimal toTableID)
        {
            return base.Channel.PrintMoveNoticeAsync(orderIDs, fromTableID, toTableID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<decimal, System.Collections.Generic.Dictionary<decimal, PosServiceReference.DBModGroup[]>>> GetModsForAllItemsAsync()
        {
            return base.Channel.GetModsForAllItemsAsync();
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.DBItem[]> GetSpecialItemsAsync()
        {
            return base.Channel.GetSpecialItemsAsync();
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.DBTable[]> GetTablesForSectionAsync(decimal sectionID)
        {
            return base.Channel.GetTablesForSectionAsync(sectionID);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeItemSizeAsync(decimal orderID, decimal newSizeID)
        {
            return base.Channel.ChangeItemSizeAsync(orderID, newSizeID);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.DBUser> GetUserAsync(string pin)
        {
            return base.Channel.GetUserAsync(pin);
        }
        
        public System.Threading.Tasks.Task<bool> CancelTakeoutAsync(decimal TakeoutGuestID)
        {
            return base.Channel.CancelTakeoutAsync(TakeoutGuestID);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.TakeoutOrder[]> GetLSEOrdersAsync()
        {
            return base.Channel.GetLSEOrdersAsync();
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.TakeoutOrder> SubmitLSETakeoutAsync(PosServiceReference.TakeoutOrder TakeoutGuest, decimal UserID)
        {
            return base.Channel.SubmitLSETakeoutAsync(TakeoutGuest, UserID);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.Guest_DB> PriceOrderAsync(PosServiceReference.Guest_DB guest)
        {
            return base.Channel.PriceOrderAsync(guest);
        }
        
        public System.Threading.Tasks.Task PrintKitchenNoteAsync(string note)
        {
            return base.Channel.PrintKitchenNoteAsync(note);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveOrderFromPlateAsync(decimal OrderID)
        {
            return base.Channel.RemoveOrderFromPlateAsync(OrderID);
        }
        
        public System.Threading.Tasks.Task<bool> AddOrderToPlateAsync(decimal OrderID, decimal PlateID)
        {
            return base.Channel.AddOrderToPlateAsync(OrderID, PlateID);
        }
        
        public System.Threading.Tasks.Task<bool> AddOrdersToPlateAsync(decimal[] orderIds, decimal plateId)
        {
            return base.Channel.AddOrdersToPlateAsync(orderIds, plateId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveMultipleFromPlateAsync(decimal[] orderIDs)
        {
            return base.Channel.RemoveMultipleFromPlateAsync(orderIDs);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.CateringOrder> SubmitCateringAsync(PosServiceReference.CateringOrder catering, decimal UserID)
        {
            return base.Channel.SubmitCateringAsync(catering, UserID);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.TakeoutOrder[]> GetCateringTakeoutsAsync()
        {
            return base.Channel.GetCateringTakeoutsAsync();
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.CateringOrder> GetCateringOrderAsync(decimal TakeoutID)
        {
            return base.Channel.GetCateringOrderAsync(TakeoutID);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.CateringOrder[]> GetAllCateringOrdersInfoAsync()
        {
            return base.Channel.GetAllCateringOrdersInfoAsync();
        }
        
        public System.Threading.Tasks.Task SendCateringTakeoutAsync(PosServiceReference.TakeoutOrder TakeoutGuest, decimal UserID)
        {
            return base.Channel.SendCateringTakeoutAsync(TakeoutGuest, UserID);
        }
        
        public System.Threading.Tasks.Task<PosServiceReference.DBTable[]> GetTableSummaryAsync()
        {
            return base.Channel.GetTableSummaryAsync();
        }
        
        public System.Threading.Tasks.Task PrintCateringOrderAsync(PosServiceReference.CateringOrder catering, decimal UserID)
        {
            return base.Channel.PrintCateringOrderAsync(catering, UserID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPosService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPosService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/WP7Waiter/POServiceHost.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PosServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPosService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PosServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPosService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPosService,
        }
    }
}
