using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using System.Threading.Tasks;
using Zipline2.Connected_Services;
using Zipline2.Models;
using Staunch.POS.Classes;

namespace Zipline2.BusinessLogic.WcfRemote
{
    public class WcfServicesProxy
    {
        #region Singleton
        private static WcfServicesProxy instance = null;
        private static readonly object padlock = new object();
      
        public static WcfServicesProxy Instance
        {
            get
            {
                lock (padlock)
                {
                    if (instance == null)
                    {
                        instance = new WcfServicesProxy();
                    }
                    return instance;
                }
            }
        }
        #endregion

        //The current Windows Phone app has a Service Reference folder with references
        //to the services.  When the services are added, the classes with references
        //are autogenerated. Then the phone app just has the following:

        private PosServiceClient waiterClient;
        private CheckHostClient checkClient;
        public Dictionary<string, DBItem[]> DBMenu;
        //public Dictionary<decimal, DBItem> MenuItemsPizza { get; private set; }
        //public Dictionary<decimal, DBItem> MenuItemsCalzone { get; private set; }
        //public Dictionary<decimal, DBItem> MenuItemsSalads { get; private set; }
        //public Dictionary<decimal, DBItem> MenuItemsBeverages { get; private set; }
        //public Dictionary<decimal, DBItem> MenuItemsDessert { get; private set; }
        private decimal UserIdDecimal;

        private WcfServicesProxy()
        {
            if (Users.Instance.LoggedInUser != null)
            {
                UserIdDecimal = Users.Instance.LoggedInUser.UserId;
            }
          
            try
            {
                waiterClient = new PosServiceClient(
                     new BasicHttpBinding(),
                     new EndpointAddress("http://192.168.1.26/WP7Waiter/POServiceHost.svc"));

                checkClient = new CheckHostClient(
                     new BasicHttpBinding(),
                     new EndpointAddress("http://192.168.1.26/CheckHost/CheckHost.svc"));
            }

            catch (Exception ex)
            {
                var errorMessage = ex;
                throw;
            }
        }

        async public Task UpdateTablesAsync(DBTable currentTable)
        {
            DBTable[] tablesToUpdate = new DBTable[] { currentTable };
            await Task.Factory.FromAsync(
                waiterClient.BeginUpdateTables,
                waiterClient.EndUpdateTables,
                tablesToUpdate,
                9M,
                TaskCreationOptions.None);
        }
       
        async public Task<DBTable> GetTableAsync(int tableNum)
        {
            
            DBTable dbTable;
            try
            {
                dbTable = await Task.Factory.FromAsync(
                    waiterClient.BeginGetTable,
                    waiterClient.EndGetTable,
                    tableNum,
                    TaskCreationOptions.None);
            }
            catch (Exception ex)
            {
                var errormessage = ex;
                throw;
            }

            return dbTable;
            //return FromWaiterService(dbTable); 
        }

        async public Task GetMenuAsync()
        {
            DBMenu = new Dictionary<string, DBItem[]>();
            try
            {
                DBMenu = await Task.Factory.FromAsync(
                    waiterClient.BeginGetMenu,
                    waiterClient.EndGetMenu,
                    null,
                    TaskCreationOptions.None);
            }
            catch (Exception ex)
            {
                var errormessage = ex;
                throw;
            }
            //foreach (var dbItem in menu["Pizza"])
            //{
            //    orderItem.MenuItems.Add(dbItem.ID, dbItem);
            //}
            //foreach (var dbItem in menu["Calzone"])
            //{
            //    MenuItemsPizza.Add(dbItem.ID, dbItem);
            //}
            //MenuItemsPizza = menu["Pizza"];
            //MenuItemsCalzone = menu["Calzone"];
            //MenuItemsSalads = menu["Salads"];
            //MenuItemsBeverages = menu["Beverages"];
            //MenuItemsDessert = menu["Dessert"];

        }

        async public Task<decimal> GetNextGuestIdAsync()
        {
            decimal[] ids = await Task.Factory.FromAsync(
                waiterClient.BeginGetNextGuestIDs,
                waiterClient.EndGetNextGuestIDs,
                1,
                UserIdDecimal,
                TaskCreationOptions.None);
            if (ids.Length > 0)
            {
                return ids[0];
            }
            return 0;
        }

        async public void SendOrderAsync(Order orderToSend)
        { 
            decimal currentTableId = OrderManager.Instance.GetCurrentTable().TableId;
            int currentTableIdAsInt = (int)currentTableId;
            
            //Create Guest_DB object.
            var guestDB = new Staunch.POS.Classes.Guest_DB()
            {
                ComboItems = new List<GuestComboItem>(),
                Items = new List<GuestItem>(),
                ID = await GetNextGuestIdAsync()
            };

            //Create DBItems for Guest_DB object.
            foreach (var orderItem in orderToSend.OrderItems)
            {
                var keysTuple = orderItem.GetMenuDbItemKeys();
                var dbItem = new DBItem();
                foreach (var menuItem in DBMenu[keysTuple.Item1])
                {
                    if (menuItem.ID == keysTuple.Item2)
                    {
                        dbItem = menuItem;
                    }
                }
                GuestItem guestItem = orderItem.CreateGuestItem(dbItem);
                guestItem.OrderSent = true;
                guestDB.Items.Add(guestItem);
            }

            //Add guestDB just created to Guests of new DBTable object.
            DBTable currentTable = new DBTable()
            {
                ID = currentTableId,
                Guests = new List<Staunch.POS.Classes.Guest_DB>()
                {
                    guestDB
                }
            };

            //Update the database table with built DBTable in order to obtain new OrderID.
            await UpdateTablesAsync(currentTable);

            //Get the table just updated - will contain new OrderID.
            DBTable thisTable = await GetTableAsync(currentTableIdAsInt);

            //Get the GuestItem obejcts from the DBTable object needed for the DBCheck.
            List<GuestItem> items = thisTable.Guests[0].Items;
            DBCheck dbCheck = new DBCheck()
            {
                ID = orderToSend.TableId,
                ComboItems = new List<GuestComboItem>(),
                Discounts = new List<OrderDiscount>(),
                GuestIDs = new List<decimal>(),
                Name = string.Empty,
                Notes = new DBNotes(),
                Items = items
            };

            //Creates and adds check to database.
            await CreateCheckAsync(dbCheck);
        }

        

        async public Task<DBUser> GetUserAsync(string pin)
        {
            return await Task.Factory.FromAsync(
                   waiterClient.BeginGetUser,
                   waiterClient.EndGetUser,
                   pin,                
                   TaskCreationOptions.None);
        }

        async public Task<DBTable[]> GetTablesForSectionAsync(decimal sectionID)
        {
            return await Task.Factory.FromAsync(
                waiterClient.BeginGetTablesForSection,
                waiterClient.EndGetTablesForSection,
                sectionID,
                TaskCreationOptions.None);
        }

        async public Task<bool> HasOpenChecksAsync(decimal tableId)
        {
            return await Task.Factory.FromAsync(
                checkClient.BeginHasOpenChecks,
                checkClient.EndHasOpenChecks,
                tableId,
                TaskCreationOptions.None);

        }

        async public Task<DBCheck[]> GetOpenChecksAsync(decimal tableId)
        {
            return await Task.Factory.FromAsync(
                checkClient.BeginGetOpenChecks,
                checkClient.EndGetOpenChecks,
                tableId,
                TaskCreationOptions.None);
        }




        async public Task CreateCheckAsync(DBCheck dbCheck)
        {
            var dbChecks = new DBCheck[]
            {
                dbCheck
            };
            try
            {
                var result = await Task.Factory.FromAsync(
                    checkClient.BeginCreateChecks,
                    checkClient.EndCreateChecks,
                    dbChecks,UserIdDecimal, false,
                    TaskCreationOptions.None);
            }
            catch (Exception ex)
            {
                var errormessage = ex;
                throw;
            }
        }
    }
}
